#!/bin/sh
# Copy tpm2_pcrextend into initrd for pigeon-verify

PREREQ=""
prereqs() { echo "$PREREQ"; }
case "$1" in prereqs) prereqs; exit 0;; esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/tpm2_pcrextend /usr/bin
