#!/bin/sh
set -e
# Extend PCR 14 with aggregate hash of critical binaries (tampered binary → LUKS won't unseal)

PREREQ=""
prereqs() { echo "$PREREQ"; }
case "$1" in prereqs) prereqs; exit 0;; esac

. /scripts/functions

BINS="
${rootmnt}/usr/bin/consul
${rootmnt}/usr/bin/nomad
${rootmnt}/usr/bin/vault
${rootmnt}/opt/pigeon/bin/pigeon-mesh
${rootmnt}/opt/pigeon/bin/pigeon-enroll
${rootmnt}/opt/pigeon/bin/pigeon-template
${rootmnt}/opt/pigeon/bin/pigeon-fence
${rootmnt}/usr/sbin/nft
${rootmnt}/usr/bin/wg
${rootmnt}/usr/local/bin/firecracker
${rootmnt}/usr/local/bin/jailer
${rootmnt}/opt/nomad/plugins/nomad-driver-firecracker
${rootmnt}/opt/nomad/plugins/nomad-plugin-lvm
"

AGGREGATE=""
for bin in $BINS; do
    if [ -f "$bin" ]; then
        BIN_HASH=$(sha256sum "$bin" | cut -d' ' -f1)
        AGGREGATE="${AGGREGATE}${BIN_HASH}"
    fi
done

if [ -z "$AGGREGATE" ]; then
    log_warning_msg "pigeon-verify: no binaries found to measure"
    exit 0
fi

HASH=$(printf '%s' "$AGGREGATE" | sha256sum | cut -d' ' -f1)
tpm2_pcrextend 14:sha256="$HASH"
log_success_msg "pigeon-verify: PCR 14 extended"
